### PR TITLE
[Changed] Encapsulation of clean none values

### PR DESCRIPTION
**Pull request by matheuslins**
:question: What
---
Create a method to encapsulate the logic of clean none values

:speech_balloon: Why
---
It's better to maintain. You need to change just in one place

**Suggestion**

What do you think in use [this lib](https://pydantic-docs.helpmanual.io/) in your API service?

In my option is better because you can make schemas validations automatically without writing **if/else statements** and you don't need to obligate the client sends a value if the key exists.

You can just make a dict passing the values of the arguments directly, like that:

**create a Link**

```python
data = {
    "institution": institution,
    "username": username,
    "password": password,
    "save_data": save_data,
    "access_mode": access_mode,
    "username2": username2,
    "password2": password2,
    "token": token,
    "encryption_key": encryption_key,
    "username_type": username_type,
    "certificate": certificate,
    "private_key": private_key,
}
```

If you do it, you can remove this method **clean_none_values** that I'm suggesting kkkk. It's simple :)

### CODE REVIEW

**Comment by menecio** [comment]
Yup, this was a TODO I had in mind after adding to the `Link` class, nevertheless, this PR will have to wait as we already are preparing to release `0.18.0`, but this could totally be part of `0.18.1`

**Comment by matheuslins** [comment]
@menecio ok, that's great!

**Comment by mcanaves** [comment]
@belvo-finance/python @matheuslins this a 4 months old PR. Could be closed or merged?

**Comment by matheuslins** [comment]
@mcanaves I don't know. @menecio  Is this PR in prd? Can we merge or close?

**Comment by mcanaves** [comment]
@matheuslins @meneciothis PR it's almost 1 year old. We should not have such old PRs.

**Pull request closed without merging**
